# Generated by Django 3.1.7 on 2021-02-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('movimentacao', models.CharField(choices=[('C', 'Cadastro'), ('S', 'Saida Manutenção'), ('E', 'Retorno Conserto'), ('D', 'Descarte ou Sem Conserto')], max_length=1)),
                ('data_movimentacao', models.DateTimeField()),
                ('data_criacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
